#!/usr/bin/env bash
set -eo pipefail

echo "-----> Installing compose"

sudo apt-get install inotify-tools -y
sudo sh -c "curl -L https://github.com/docker/compose/releases/download/1.1.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose"
sudo chmod +x /usr/local/bin/docker-compose
sudo mkdir /opt/compose

sudo cp file/compose.upstart.conf /etc/init/compose.conf
