#!/usr/bin/env bash
set -eo pipefail

echo "-----> Installing fig"

sudo apt-get install inotify-tools -y
sudo sh -c "curl -L https://github.com/docker/fig/releases/download/1.0.1/fig-`uname -s`-`uname -m` > /usr/local/bin/fig"
sudo chmod +x /usr/local/bin/fig
sudo mkdir /opt/fig

sudo cp file/fig.upstart.conf /etc/init/fig.conf
